name: Docker Image CI

on:
  schedule:
    - cron: '0 5 * * *'
  push:
    branches: [ master ]

env:
  DOCKER_REPOSITORY: msansen/symfony-cli

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to github registry
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build :latest
      if: success()
      run: docker build -t ${DOCKER_REPOSITORY}:latest .

    - name: Push to docker hub :latest
      if: success()
      uses: actions-hub/docker@master
      with:
        args: push ${DOCKER_REPOSITORY}:latest
