name: Docker Image CI

on:
  schedule:
    - cron: '0 5 * * *'
  push:
    branches: [ master ]

env:
  DOCKER_REPOSITORY: msansen/symfony-cli

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "7.4", "8.0", "8.1", "8.2", "8.3" ]
    steps:
    - uses: actions/checkout@v2
    - name: Login to github registry
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build :version
      if: success()
      run: docker build --build-arg PHP_VERSION=${{ matrix.version }} -t ${DOCKER_REPOSITORY}:${{ matrix.version }} .

    - name: Push to docker hub :version
      if: success()
      uses: actions-hub/docker@master
      with:
        args: push ${DOCKER_REPOSITORY}:${{ matrix.version }}

    - name: Build :version
      if: ${{ success() && matrix.version == '8.2' }}
      run: docker tag ${DOCKER_REPOSITORY}:${{ matrix.version }} ${DOCKER_REPOSITORY}:latest

    - name: Push to docker hub :latest
      if: ${{ success() && matrix.version == '8.2' }}
      uses: actions-hub/docker@master
      with:
        args: push ${DOCKER_REPOSITORY}:latest
